name: Build, publish and release
on:
  push:
    tags:
      - v*.*.*  # only on release tags

jobs:
  build:
    uses: MDL-Viewer/hott-util/.github/workflows/build.yaml@main
    secrets: inherit
    permissions:
      contents: write
      packages: write